### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by ttyfly** [wjy-yy/crawl1#1]
写得很好，基本符合要求。

json 输出时，请注意 content 内容的换行问题。如果 json 的引号间存在换行，请转化为 \n，不然识别会出错。

另外，编写功能前可以去看看标准库里有没有已经实现好的函数。比如 python 的 json 库。

修改完后，可以直接在此 issue 下发表回复，我会再次查看。

**Comment by wjy-yy** [comment]
学长好，已经将`\n`、`\'`、`\"`三种字符全部转化为相应字符，也已经使用json库优化代码，最新文件为`main1.3.py`。

**Comment by ttyfly** [comment]
> 
> 
> 学长好，已经将`\n`、`\'`、`\"`三种字符全部转化为相应字符，也已经使用json库优化代码，最新文件为`main1.3.py`。

已查看，完成度很高。感谢您的参与。后续会公布参考代码和夏令营优秀营员名单，敬请关注。
